# Generated by Django 4.2 on 2023-04-14 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('littlelemonAPI', '0003_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order',)},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='littlelemonAPI.cart'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='menuitem',
        ),
    ]
