# Generated by Django 4.2 on 2023-04-14 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonAPI', '0004_alter_orderitem_unique_together_orderitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menuitem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='littlelemonAPI.menuitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='littlelemonAPI.order'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'menuitem')},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cart',
        ),
    ]
